# Generated by Django 5.0.1 on 2024-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="books", to="book.author"),
        ),
    ]
